# Automatically generated by build.py on 2025-04-04
# This file contains version information for SPT Asset Editor

__version__ = "1.1.0"
__app_name__ = "SPTAssetEditor"
__description__ = "SPT Asset Editor is a tool for viewing and editing textures in Tarkov game files."
__author__ = "Golani11"
__copyright__ = "© 2025 Golani11. All rights reserved."
__license__ = "MIT"
__build_date__ = "2025-04-04"
__website__ = "https://github.com/Golani11/SPT_Asset_Editor"
